/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layouts/AppHeader.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    AppSidebar: typeof import('./src/components/layouts/AppSidebar.vue')['default']
    BaseBadge: typeof import('./src/components/base/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    ErrorAlert: typeof import('./src/components/ui/ErrorAlert.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenuItem: typeof import('./src/components/layouts/SidebarMenuItem.vue')['default']
  }
}
