/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/layouts/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layouts/AppSidebar.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    ConfirmDialog: typeof import('./src/components/ui/ConfirmDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./src/components/ui/EmptyState.vue')['default']
    ErrorAlert: typeof import('./src/components/ui/ErrorAlert.vue')['default']
    LoadingSpinner: typeof import('./src/components/ui/LoadingSpinner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
